# Base image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# copy src
COPY .. .

# install initial depenancies
RUN npm install

# install production depencancies
RUN npm install --omit=dev

# build
RUN npm run build


#pull nginx as webser and load balancer
FROM nginx:stable-alpine3.20-slim

RUN apk update && apk upgrade --no-cache

# copy the build files to nginx entry point
COPY ./dist /usr/share/nginx/html
